#!/usr/bin/env ruby
$LOAD_PATH.unshift File.expand_path("../../gems/bundler/lib", __FILE__)
require 'rubygems'
require 'rubygems/command'
require 'bundler'
require 'bundler/commands/bundle_command'
Gem::Commands::BundleCommand.new.invoke(*ARGV)
